name: handle manifest PR
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:
      - main
      - v3.7.99-ncs1-branch
      

jobs:
  call-manifest-pr-action:
    runs-on: ubuntu-latest
    env:
      TARGET_BASE_BRANCH: ${{ github.ref == 'refs/heads/v3.7.99-ncs1-branch' && 'v2.8-branch' || 'main' }}
      # myjson: '{"v3.7.99-ncs1-branch" : "v2.8-branch", "v3.7.99-ncs1-branch": "v2.7-branch"}'
    steps:
      - name: set TARGET_BASE_BRANCH
        run: echo "TARGET_BASE_BRANCH=${{ TARGET_BASE_BRANCH }}
      # if: contains(['SNAPSHOT'],env.BUILD_VERSION)
      # run: echo '{{ github.event.pull_request.base.ref}}'
      # run: echo "TARGET_BASE_BRANCH=${{ fromJSON(env.myjson)[env.var_foo] }}" >> $GITHUB_ENV
      
      - name: handle manifest PR
        uses: thst-nordic/action-manifest-pr@add_release_branches
        with:
          token: ${{ secrets.NCS_GITHUB_TOKEN }}
          manifest-pr-title-details: ${{ github.event.pull_request.title }}
          target-repo: nrfconnect/sdk-nrf-testing
          forked-repo: nordicbuilder/sdk-nrf-testing
          base-branch: ${{ TARGET_BASE_BRANCH }}
