name: handle manifest PR
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:
      - main
      - v3.7.99-ncs1-branch


jobs:
  call-manifest-pr-action:
    runs-on: ubuntu-latest
    steps:
      - name: handle manifest PR
        uses: nrfconnect/action-manifest-pr@main
        with:
          token: ${{ secrets.NCS_GITHUB_TOKEN }}
          manifest-pr-title-details: ${{ github.event.pull_request.title }}
          target-repo: nrfconnect/sdk-nrf-testing
          forked-repo: nordicbuilder/sdk-nrf-testing
